export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { getSessionAppUserId } from "../../../lib/auth/get-session-app-user-id";
import { supabaseAdmin } from "../../../lib/supabase-server";

/**
 * GET /api/superbill?provider_id=...&visit_id=...
 *
 * Generates a printable superbill HTML that the user can save as a
 * PDF (browser print dialog → save as PDF) and submit to their
 * insurance for out-of-network reimbursement.
 *
 * Phase 0: HTML render only. The user's browser handles the PDF
 * conversion — keeps us off any PDF library / native dependency.
 *
 * Form follows the typical out-of-network reimbursement format:
 * patient block, provider block, services rendered (date, CPT, ICD,
 * charge), totals. CPT/ICD codes are filled if Kate captured them
 * during a call; otherwise blanked for the user to fill in.
 */

function fmtMoney(n: number | null | undefined): string {
  if (n == null || isNaN(Number(n))) return "$_____";
  return `$${Number(n).toFixed(2)}`;
}

function fmtDate(iso: string | null | undefined): string {
  if (!iso) return "____________";
  return new Date(iso).toLocaleDateString("en-US", {
    month: "2-digit",
    day: "2-digit",
    year: "numeric",
  });
}

export async function GET(req: NextRequest) {
  const appUserId = await getSessionAppUserId(req);
  if (!appUserId) {
    return new Response("Unauthorized", { status: 401 });
  }

  const url = new URL(req.url);
  const providerId = url.searchParams.get("provider_id");
  const visitId = url.searchParams.get("visit_id"); // optional: specific visit
  if (!providerId) {
    return new Response("Missing provider_id", { status: 400 });
  }

  // Patient
  const { data: appUser } = await supabaseAdmin
    .from("app_users")
    .select("patient_profile, auth_user_id")
    .eq("id", appUserId)
    .maybeSingle();
  const profile = (appUser?.patient_profile ?? {}) as Record<string, unknown>;
  const fullName =
    (profile.full_name as string) ||
    [profile.first_name, profile.last_name].filter(Boolean).join(" ") ||
    "[Patient name]";

  // Provider
  const { data: provider } = await supabaseAdmin
    .from("providers")
    .select("name, doctor_name, npi, phone_number, address, provider_type, tax_id")
    .eq("id", providerId)
    .eq("app_user_id", appUserId)
    .maybeSingle();
  if (!provider) {
    return new Response("Provider not found", { status: 404 });
  }

  // Visits — either a single specific visit or all visits with this provider.
  const visitQuery = supabaseAdmin
    .from("provider_visits")
    .select("id, visit_date, amount, cpt_code, icd_code")
    .eq("app_user_id", appUserId)
    .eq("provider_id", providerId)
    .order("visit_date", { ascending: false });
  if (visitId) visitQuery.eq("id", visitId);
  const { data: visits } = await visitQuery;

  const visitRows = visits ?? [];
  const totalCharges = visitRows.reduce((sum, v) => sum + (Number(v.amount) || 0), 0);

  // Super-minimal HTML — user prints from browser, page is sized for letter
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Superbill — ${fullName}</title>
<style>
  @media print { @page { size: letter; margin: 0.5in; } }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
    color: #071832; max-width: 7.5in; margin: 0 auto; padding: 24px; font-size: 13px;
    line-height: 1.5; }
  h1 { font-size: 22px; margin: 0 0 4px; letter-spacing: -0.3px; }
  h2 { font-size: 11px; text-transform: uppercase; letter-spacing: 1.5px; margin: 24px 0 8px;
    color: #4F5F73; font-weight: 700; }
  .row { display: flex; gap: 12px; margin: 6px 0; }
  .row .label { min-width: 140px; font-weight: 600; color: #4F5F73; }
  .row .val { flex: 1; color: #071832; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #E5EAF2;
    font-size: 12.5px; }
  th { font-size: 10.5px; text-transform: uppercase; letter-spacing: 0.8px;
    color: #4F5F73; font-weight: 700; background: #FAF8F4; }
  td.amount, th.amount { text-align: right; font-variant-numeric: tabular-nums; }
  .total { background: #FAF8F4; font-weight: 700; }
  .footer-note { margin-top: 28px; font-size: 11px; color: #4F5F73;
    border-top: 1px dashed #E5EAF2; padding-top: 16px; }
  .actions { margin: 16px 0; }
  .actions button { background: #1677FF; color: #fff; border: none; padding: 10px 18px;
    border-radius: 10px; font-size: 14px; font-weight: 600; cursor: pointer; }
  @media print { .actions { display: none; } }
</style>
</head>
<body>
  <div class="actions">
    <button onclick="window.print()">Save / print as PDF</button>
  </div>

  <h1>Superbill</h1>
  <div style="color: #4F5F73; font-size: 12px;">Generated by Quarterback Health · ${new Date().toLocaleDateString(
    "en-US",
    { month: "long", day: "numeric", year: "numeric" }
  )}</div>

  <h2>Patient</h2>
  <div class="row"><div class="label">Name</div><div class="val">${fullName}</div></div>
  <div class="row"><div class="label">Date of birth</div><div class="val">${
    fmtDate(profile.date_of_birth as string | null)
  }</div></div>
  <div class="row"><div class="label">Address</div><div class="val">${
    (profile.address as string) || "____________________________________"
  }</div></div>
  <div class="row"><div class="label">Phone</div><div class="val">${
    (profile.callback_phone as string) || (profile.phone as string) || "______________"
  }</div></div>

  <h2>Provider</h2>
  <div class="row"><div class="label">Practice</div><div class="val">${provider.name || ""}</div></div>
  ${provider.doctor_name ? `<div class="row"><div class="label">Doctor</div><div class="val">${provider.doctor_name}</div></div>` : ""}
  <div class="row"><div class="label">NPI</div><div class="val">${provider.npi || "______________"}</div></div>
  <div class="row"><div class="label">Tax ID (EIN)</div><div class="val">${provider.tax_id || "______________"}</div></div>
  <div class="row"><div class="label">Address</div><div class="val">${provider.address || "____________________________________"}</div></div>
  <div class="row"><div class="label">Phone</div><div class="val">${provider.phone_number || "______________"}</div></div>

  <h2>Services rendered</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>CPT code</th>
        <th>Diagnosis (ICD-10)</th>
        <th class="amount">Charge</th>
      </tr>
    </thead>
    <tbody>
      ${
        visitRows.length === 0
          ? `<tr><td colspan="3" style="color:#4F5F73; font-style:italic;">No visits on file — fill in manually below</td><td class="amount">$_____</td></tr>`
          : visitRows
              .map(
                (v) => `<tr>
        <td>${fmtDate(v.visit_date)}</td>
        <td>${v.cpt_code || "___________"}</td>
        <td>${v.icd_code || "___________"}</td>
        <td class="amount">${fmtMoney(Number(v.amount))}</td>
      </tr>`
              )
              .join("")
      }
      <tr class="total">
        <td colspan="3">Total</td>
        <td class="amount">${fmtMoney(totalCharges)}</td>
      </tr>
    </tbody>
  </table>

  <h2>Insurance</h2>
  <div class="row"><div class="label">Insurance carrier</div><div class="val">${
    (profile.insurance_provider as string) || "______________"
  }</div></div>
  <div class="row"><div class="label">Member ID</div><div class="val">${
    (profile.insurance_member_id as string) || "______________"
  }</div></div>
  <div class="row"><div class="label">Group #</div><div class="val">${
    (profile.insurance_group_number as string) || "______________"
  }</div></div>

  <div class="footer-note">
    <strong>How to use this superbill:</strong> Submit to your insurance company through
    their member portal, mobile app, or the address on the back of your insurance card.
    Most insurers accept superbills via online form upload. CPT and ICD-10 codes are
    required by most insurers for reimbursement — if any are blank, ask your provider's
    office to fill them in before submitting.
  </div>
</body>
</html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
